import React from 'react';
import '../../responsive-style.css';
import { Logo } from '../../components/Logo';
import { Navigation } from '../../components/Navigation';
import { Footer } from '../../components/Footer';

export const MFAPage = () => {
  return (
    <div className="landing-page">
      {/* Header */}
      <header className="sticky-header">
        <div className="header-content">
          <div className="logo">
            <Logo />
          </div>
          <Navigation />
        </div>
      </header>

      <main className="main-content">
        {/* Hero Section */}
        <section className="hero-section">
          <div className="container">
            <div className="hero-content">
              <h1>Multi-Factor Authentication for New Brunswick Businesses</h1>
              <p className="hero-subheadline">
                Add critical layers of security beyond passwords with professional MFA implementation. 
                Protect your business systems in Fredericton, Moncton, Saint John, and across New Brunswick.
              </p>
              <div className="hero-cta-section">
                <a href="/contact" className="btn btn-primary btn-hero">Get MFA Implementation Quote</a>
                <a href="/contact" className="secondary-link">Ask About Grant Eligibility →</a>
              </div>
            </div>
          </div>
        </section>

        {/* Why MFA Matters Statistics */}
        <section className="section" style={{ backgroundColor: '#fff3cd' }}>
          <div className="container">
            <div className="section-header" style={{ marginBottom: '40px' }}>
              <h2 className="section-title">Why Multi-Factor Authentication is Essential</h2>
            </div>
            <div className="features-grid animate-on-scroll">
              <div className="feature-item" style={{ textAlign: 'center' }}>
                <h3>99.9%</h3>
                <p>of password attacks can be blocked by MFA</p>
              </div>
              <div className="feature-item" style={{ textAlign: 'center' }}>
                <h3>80%</h3>
                <p>of data breaches involve compromised credentials</p>
              </div>
              <div className="feature-item" style={{ textAlign: 'center' }}>
                <h3>50%</h3>
                <p>increase in cyber attacks on small businesses</p>
              </div>
            </div>
            <div style={{ textAlign: 'center', marginTop: '30px' }}>
              <p style={{ fontSize: '1.1rem', color: '#666', maxWidth: '600px', margin: '0 auto' }}>
                Multi-Factor Authentication is your most effective defense against account takeovers, 
                even when passwords are compromised.
              </p>
            </div>
          </div>
        </section>

        {/* What is MFA */}
        <section className="section">
          <div className="container">
            <div className="section-header" style={{ marginBottom: '40px' }}>
              <h2 className="section-title">What is Multi-Factor Authentication?</h2>
              <p style={{ fontSize: '1.1rem', color: '#666', maxWidth: '700px', margin: '0 auto' }}>
                MFA requires multiple forms of verification before accessing systems, combining something you know 
                with something you have or something you are for maximum security.
              </p>
            </div>
            <div className="services-grid animate-on-scroll">
              <div className="service-card">
                <div className="service-icon floating-icon">📱</div>
                <h3>Mobile Authenticator Apps</h3>
                <p>
                  Time-based codes generated by apps like Microsoft Authenticator or Google Authenticator. 
                  Works offline and provides excellent security.
                </p>
                <div className="feature-highlight">Most Secure Method</div>
              </div>
              <div className="service-card">
                <div className="service-icon floating-icon">🔑</div>
                <h3>Hardware Security Keys</h3>
                <p>
                  Physical devices like YubiKey that provide the highest level of security. 
                  Ideal for high-privilege accounts and sensitive data access.
                </p>
                <div className="feature-highlight">Highest Security</div>
              </div>
              <div className="service-card">
                <div className="service-icon floating-icon">👆</div>
                <h3>Biometric Authentication</h3>
                <p>
                  Fingerprint, face recognition, or voice authentication. 
                  Convenient and secure for device-based access control.
                </p>
                <div className="feature-highlight">Very Convenient</div>
              </div>
            </div>
          </div>
        </section>

        {/* Benefits */}
        <section className="section" style={{ backgroundColor: '#f8f9fa' }}>
          <div className="container">
            <div className="section-header" style={{ marginBottom: '40px' }}>
              <h2 className="section-title">Benefits of Professional MFA Implementation</h2>
            </div>
            <div className="features-grid animate-on-scroll">
              <div className="feature-item">
                <h3>🛡️ Prevent Account Takeovers</h3>
                <p>
                  Even if passwords are compromised, attackers cannot access your systems without 
                  the additional authentication factors your employees control.
                </p>
              </div>
              <div className="feature-item">
                <h3>📋 Meet Compliance Requirements</h3>
                <p>
                  Many industry regulations and insurance policies now require MFA for accessing 
                  sensitive data and systems. Stay compliant and reduce liability.
                </p>
              </div>
              <div className="feature-item">
                <h3>💰 Reduce Security Incidents</h3>
                <p>
                  Dramatically decrease the likelihood of successful cyber attacks, data breaches, 
                  and the associated costs of incident response and recovery.
                </p>
              </div>
            </div>
            <div className="cta-buttons">
              <a href="/contact" className="btn btn-primary">Get MFA Implementation</a>
              <a href="/contact" className="btn btn-secondary">Ask About Grants</a>
            </div>
          </div>
        </section>

        {/* Implementation Process */}
        <section className="section">
          <div className="container">
            <div className="section-header" style={{ marginBottom: '40px' }}>
              <h2 className="section-title">Our MFA Implementation Process</h2>
              <p style={{ fontSize: '1.1rem', color: '#666', maxWidth: '600px', margin: '0 auto' }}>
                Professional multi-factor authentication implementation for New Brunswick businesses
              </p>
            </div>
            <div className="services-grid animate-on-scroll">
              <div className="service-card">
                <div className="service-icon floating-icon">1️⃣</div>
                <h3>Security Assessment</h3>
                <p>
                  Evaluate current authentication methods, identify critical access points, 
                  and determine the best MFA solution for your business systems.
                </p>
              </div>
              <div className="service-card">
                <div className="service-icon floating-icon">2️⃣</div>
                <h3>Solution Design & Deployment</h3>
                <p>
                  Design comprehensive MFA strategy and deploy solutions across all business-critical 
                  applications with proper integration and minimal disruption.
                </p>
              </div>
              <div className="service-card">
                <div className="service-icon floating-icon">3️⃣</div>
                <h3>Training & Ongoing Support</h3>
                <p>
                  Comprehensive user training and ongoing support to ensure smooth adoption 
                  and maximum security effectiveness of your MFA implementation.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Local Service Areas */}
        <section className="section" style={{ backgroundColor: '#f0f9ff' }}>
          <div className="container">
            <div className="section-header" style={{ marginBottom: '40px' }}>
              <h2 className="section-title">MFA Services Across New Brunswick</h2>
              <p style={{ fontSize: '1.1rem', color: '#666', maxWidth: '700px', margin: '0 auto' }}>
                Professional multi-factor authentication services for businesses throughout New Brunswick
              </p>
            </div>
            <div className="features-grid animate-on-scroll">
              <div className="feature-item" style={{ textAlign: 'center' }}>
                <h3>🏛️ Fredericton Region</h3>
                <p>
                  Supporting government contractors and professional services with MFA solutions 
                  that meet provincial security standards and compliance requirements.
                </p>
              </div>
              <div className="feature-item" style={{ textAlign: 'center' }}>
                <h3>🏭 Moncton Area</h3>
                <p>
                  Helping manufacturing and logistics companies protect operational systems 
                  with robust multi-factor authentication solutions.
                </p>
              </div>
              <div className="feature-item" style={{ textAlign: 'center' }}>
                <h3>⚓ Saint John</h3>
                <p>
                  Providing maritime and energy sector businesses with secure authentication 
                  solutions that protect critical infrastructure and operations.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Final CTA */}
        <section className="section">
          <div className="container">
            <div className="section-header" style={{ marginBottom: '30px' }}>
              <h2 className="section-title">Ready to Add Critical Security Layers?</h2>
              <p style={{ fontSize: '1.1rem', color: '#666', maxWidth: '600px', margin: '0 auto' }}>
                Protect your New Brunswick business with professional multi-factor authentication implementation
              </p>
            </div>
            <div className="cta-buttons">
              <a href="/contact" className="btn btn-primary">Get MFA Implementation Quote</a>
              <a href="/contact" className="btn btn-secondary">Learn About Grant Funding</a>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};